###################################################
# @file   : tmux.conf
# @brief  : Config file for tmux.
###################################################

# General
set -g default-terminal "tmux-256color"  # Use tmux's terminfo entry.
set -ga terminal-overrides ",*:RGB"      # Enable true-color (24-bit RGB).
set -g status-position top               # Place the status bar at the top.
set -g status-interval 5                 # Refresh status line more often.
set -sg escape-time 0                    # Remove Escape key delay.
set -g focus-events on                   # Forward terminal focus events.
set -g extended-keys on                  # Enable extended keyboard support.
set -g set-clipboard on                  # Sync with the system clipboard.
set -g mouse on                          # Enable mouse support.
set -g base-index 1                      # Start window numbering at 1.
set -wg pane-base-index 1                # Start pane numbering at 1.
set -g renumber-windows on               # Renumber windows after closing.
set -g aggressive-resize on              # Resize windows to match the client.
set -g bell-action none                  # Silence the terminal bell.
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Configuration reloaded"
bind y setw synchronize-panes \; display-message "Sync: #{?synchronize-panes,ON,OFF}"

# Panes
bind s split-window -h        # Split horizontally.   (Default: <prefix> + ")
bind v split-window -v        # Split vertically.     (Default: <prefix> + %)
bind h select-pane -L         # Select left pane.     (Default: <prefix> + ←)
bind j select-pane -D         # Select lower pane.    (Default: <prefix> + ↓)
bind k select-pane -U         # Select upper pane.    (Default: <prefix> + ↑)
bind l select-pane -R         # Select right pane.    (Default: <prefix> + →)
bind x kill-pane              # Close current pane.   (Default: <prefix> + x)

# Windows
bind -n C-h previous-window   # Previous window.      (Default: <prefix> + p)
bind -n C-l next-window       # Next window.          (Default: <prefix> + n)
bind q kill-window            # Close current window. (Default: <prefix> + &)

# Vim Mode
set -wg mode-keys vi                                              # Use vim keys in Copy Mode.
set -g status-keys vi                                             # Use vim keys in Command Mode.
bind Enter copy-mode                                              # Enter Copy Mode.
bind-key -T copy-mode-vi v send-keys -X begin-selection           # Begin selection. (Default: Space)
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel # Copy selection.  (Default: Enter)
bind-key -T copy-mode-vi Escape send-keys -X cancel               # Exit Copy Mode.  (Default: q)
